DROP TABLE IF EXISTS tokens;
DROP TABLE IF EXISTS users;


CREATE TABLE IF NOT EXISTS users 
(
    id INT PRIMARY KEY AUTO_INCREMENT,
    fullName VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    isVerified BOOLEAN DEFAULT FALSE,
    password VARCHAR(255) NOT NULL,
    role ENUM('USER', 'ADMIN') DEFAULT 'USER'
);

CREATE TABLE IF NOT EXISTS tokens
(
    id INT PRIMARY KEY AUTO_INCREMENT,
    userId INT UNIQUE,
    token VARCHAR(512) NOT NULL,
    expiresAt TIMESTAMP NOT NULL,

    CONSTRAINT fk_user FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);